import Head from 'next/head'

export default function Home() {
   return (
      <div>
         <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <meta charset="utf-8" />
         </Head>

         
      </div>
   )
}
